### ISSUE TITLE
Unable to detect my reader

### ISSUE THREAD

**Issue by rahul1205** [LudovicRousseau/pcsc-tools#10]
Hi,
I am using an ACR122U with this tool. I already unloaded the kernel as you mentioned but am getting this error trace as soon as I plug in my reader. 
rahul@rahul-Lenovo-B40-70:~/Desktop/nfctools-examples/src/main/java/org/nfctools/examples/ndefreader$ pcsc_scan
PC/SC device scanner
V 1.4.22 (c) 2001-2011, Ludovic Rousseau <ludovic.rousseau@free.fr>
Compiled with PC/SC lite version: 1.8.10
Using reader plug'n play mechanism
Scanning present readers...
Waiting for the first reader...found one
Scanning present readers...
0: ACS ACR122U 00 00

Sat Oct 28 10:47:30 2017
Reader 0: ACS ACR122U 00 00
  Card state: 
SCardGetStatusChange: Unknown reader specified.

Kindly help we with this.

**Comment by LudovicRousseau** [comment]
Please provide the information as detailed in https://pcsclite.alioth.debian.org/ccid.html#support

**Comment by rahul1205** [comment]
@LudovicRousseau 
Hi,
Kindly close this issue. I got my error and everything works fine for now. However, the hardware itself doesn't register onto usbserial module of ubuntu. Any ideas on how to fix this.?
