### ISSUE TITLE
missing file "Changelog" in version 1.4.27

### ISSUE THREAD

**Issue by pedrospace** [LudovicRousseau/pcsc-tools#13]
Hello Ludovic, first I would like to thank you for this tool, I am using it on Slackware to use my ID card reader for e-goverment services. The version I did build for Slackware 14.2 is 1.4.27, but failed on first build, because of missing Changelog file. I added one from 1.5.2 version and all went well. There is also seccond issue, the folder name in packed source is doubled "pcsc-tools-pcsc-tools-1.4.27" not a big deal for me, but all the distribution related automatic scripts for building the package expect correct folder name. Attached is corrected src. Hope I did it in correct way, I use GitHub for first time and I am not a developer or  programmer, just linux user.
[pcsc-tools-1.4.27.tar.gz](https://github.com/LudovicRousseau/pcsc-tools/files/1509584/pcsc-tools-1.4.27.tar.gz)

**Comment by LudovicRousseau** [comment]
The latest version is 1.5.2 and you can get it from http://ludovic.rousseau.free.fr/softwares/pcsc-tools/

To build it just do:
- configure
- make
- make install

Where did you got version 1.4.27?

**Comment by pedrospace** [comment]
Hello, I know about new version, but I wanted to create slackware package
for which I have receip, to be able to install it by distro related package
management.
 1.4.27 I have from here:
https://github.com/LudovicRousseau/pcsc-tools/releases

Thanks,
Peter

**Comment by LudovicRousseau** [comment]
OK.
Files at https://github.com/LudovicRousseau/pcsc-tools/releases are automatically created by github itself. Do not use them.

Unfortunately the version 1.4.27 is no more available on my web site.
But you can get the archive from http://cdn-fastly.deb.debian.org/debian/pool/main/p/pcsc-tools/ for example.

**Comment by pedrospace** [comment]
Clear, many thanks.
Peter
