### ISSUE TITLE
Submitting unknown cards info requires access to you Google account

### ISSUE THREAD

**Issue by coquec** [LudovicRousseau/pcsc-tools#15]
I've tried to submit a Spanish ING DIRECT MasterCard info at http://smartcard-atr.appspot.com/parse?ATR=3B8C8001504F3BF0CD0000000080817164, only to find I had to log in my Google account and to allow an unnamed application to access my account information. I can't send the data without allowing this permission, which I won't do.

Is there any other way to send the info? If there are, say it in the pcsc_scan output, please.

Thanks.

**Comment by LudovicRousseau** [comment]
I added a new button so that you can submit an new ATR if you have no Google account (or don't want to use it).

For your information: I only get the account user name so I can (try to) contact the user to get more details if needed.
