### ISSUE TITLE
Update of smartcard_list.txt

### ISSUE THREAD

**Issue by laurentalacoque** [LudovicRousseau/pcsc-tools#18]
I own a Transisère card from OùRA network.
Its ATS is `3B 6F 00 00 80 5A 0A 01 02 20 03 11 .. .. .. .. 82 90 00`, where the `.. .. .. ..` represents the tag identifier (Converted to decimal, this is the number that is physically printed on the card)

I therefore suggest to change the description here:
https://github.com/LudovicRousseau/pcsc-tools/blob/5827d108b3f59adf8e2468d6b18f411d31ec32c0/smartcard_list.txt#L2892

to this:
```
« Oùra ! » Card of region Rhône-Alpes (SNCF, Transisère), Calypso standard
```

**Comment by LudovicRousseau** [comment]
Thanks. I updated the list.
https://smartcard-atr.appspot.com/parse?ATR=3B6F0000805A0A010220031101020304829000

**Comment by laurentalacoque** [comment]
One final thought : the link you provided states TER as operator for this scheme.

As I mentioned above, Transisère coach network also use the same ATR (as many others surely).

I feel that the `Transport Express Régional (TER)` part is a bit restrictive ;)

**Comment by LudovicRousseau** [comment]
It should be OK now
https://smartcard-atr.appspot.com/parse?ATR=3B6F0000805A0A010220031101020304829000
