### ISSUE TITLE
Can't find my reader after replug

### ISSUE THREAD

**Issue by kolayne** [LudovicRousseau/pcsc-tools#20]
I plug in the reader. Then I do
```
sudo rmmod pn533_usb
sudo rmmod pn533
pcsc_scan
```
And it sees my reader! It sees changes with card state and so on. This works great. I can restart pcsc_scan and it will still see my reader. BUT if I replug my reader, after that pcsc_scan is just waiting for a reader. I thought, it might be that kernel restarts pn533 mods, so I removed them again, but it didn't work. It could find my reader again only after reboot...

I'm using Linux Mint 19, ACR122U reader.

**Comment by LudovicRousseau** [comment]
https://ccid.apdu.fr/#support

**Comment by LudovicRousseau** [comment]
The pn533 and pn533_usb modules is automatically reloaded when the reader is re-plugged. Remove them from the disk.

**Comment by LudovicRousseau** [comment]
Something like:
```
rm -r /lib/modules/4.9.0-8-amd64/kernel/drivers/nfc/pn533
```

**Comment by kolayne** [comment]
Thank you VERY MUCH! Removing of pn533 fixed this problemб the previous problem and another small one

**Comment by LudovicRousseau** [comment]
I updated https://ludovicrousseau.blogspot.com/2013/11/linux-nfc-driver-conflicts-with-ccid.html
