### ISSUE TITLE
Wrong information on "Skatteverkets identitetskort"?

### ISSUE THREAD

**Issue by Grimler91** [LudovicRousseau/pcsc-tools#22]
Hi, 

I have a e-id from the Swedish authority Skatteverket. When I scan for the card for pcsc_scan it shows up as: 
```
3B 7F 96 00 00 80 31 80 65 B0 85 03 00 EF 12 0F FF 82 90 00
	Portuguese Blood Donator National Card (HealthCare)
	Skatteverkets identitetskort för folkbokförda i Sverige (utfärdade fr.o.m. september 2017) med AB Svenska Pass e-legitimation
	https://skatteverket.se/privat/folkbokforing/idkort/elegitimationpaidkortet.4.3810a01c150939e893f8169.html
```

Is the same card ID used for Portuguese Blood Donators or has there been a copy&paste error here?

The information was added in 741f3c15 and 3f7c5ce6. 741f3c15 also added [information on another Swedish e-id](https://github.com/LudovicRousseau/pcsc-tools/blob/5ef83b8469dabbbcf140e0a85712e88927dd1161/smartcard_list.txt#L4211) which, to my knowledge, does not exist, and has not existed. I tried googling, in Swedish, for information on such a card but came up with zero hits. 

So, is it possible that there's been a mix-up in the list here?

**Comment by LudovicRousseau** [comment]
The same ATR can be used by different cards.
What description should I use for your card?

**Comment by Grimler91** [comment]
Alright, thanks for the information!

The current description is accurate, it explains that the ID comes from Skatteverket and that is also has an e-id from AB Svenska Pass.

It could perhaps be shortened to: 
```
Skatteverkets identitetskort med AB Svenska Pass e-legitimation (utfärdade fr.o.m. september 2017)
```

Or would you prefer an English version?

**Comment by LudovicRousseau** [comment]
An English version is preferred :-)

**Comment by Grimler91** [comment]
Then I propose:
```
Swedish ID card from Skatteverket with an Electronic ID from AB Svenska Pass, issued September 2017 or later
```
👍

**Comment by LudovicRousseau** [comment]
Fixed. Thanks
