### ISSUE TITLE
How do you compile the tools

### ISSUE THREAD

**Issue by WattsC-90** [LudovicRousseau/pcsc-tools#25]
Hi,

I am a windows developer, so apologies for the eye rolling question.. but how do you compile the tools? 

I have tried `./compile` , but it requires arguments.. have tried `make -f Makefile.am` but this just prints.. `make: 'Changelog' is up to date.` 

If I run `make -f Makefile.am pcsc_scan`, it prints.. `Fatal Error: winscard.h: no such file or directory.

I am running on raspberry pi, just trying to validate that the hardware is working before trying to go any further..

**Comment by LudovicRousseau** [comment]
Get the `.tar.bz2` from http://ludovic.rousseau.free.fr/softwares/pcsc-tools/ and use the classic:
```
./configure
make
```

If you use Raspbian on your raspberry Pi you can just install the pcsc-tools package.

**Comment by WattsC-90** [comment]
Thanks, installed the package now, but even with configure and make I still got winscard.h fatal error

`./configure
make pscs_scan`

results in the winscard.h error on a pi.

**Comment by LudovicRousseau** [comment]
Install the package that provides winscard.h. It is libpcsclite-dev

**Comment by WattsC-90** [comment]
Thank you
