### ISSUE TITLE
Android/Termux: pcsc_scan does not find SCM SPR332 v2 card reader

### ISSUE THREAD

**Issue by feklee** [LudovicRousseau/pcsc-tools#28]
In the past, i.e. about a year ago and with an older phone and Android version, the reader worked fine with GnuPG. Now I cannot get it to work, even on the old phone. Possibly with Android Pie something has changed.

Versions
========

  * libccid 1.4.31 (Termux package)

  * pcscd 1.8.25 (Termux root package)

  * `"$PREFIX/bin/pcscd" --version`:
  
        pcsc-lite version 1.8.25.
        Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
        Copyright (C) 2001-2018 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
        Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
        Report bugs to <pcsclite-muscle@lists.alioth.debian.org>.
        Enabled features: Linux aarch64-unknown-linux-android serial usb libusb usbdropdir=/data/data/com.termux/files/usr/lib/pcsc/drivers ipcdir=/data/data/com.termux/files/usr/var/run configdir=/data/data/com.termux/files/usr/etc/reader.conf.d

  * `pcsc_scan`: compiled from source package `pcsc-tools-1.5.4.tar.bz2`

Platform
========

  * Operating system or GNU/Linux distribution name and version:
  
      + `uname -a`: `Linux localhost 4.9.106-perf+ #1 SMP PREEMPT Thu Aug 1 20:20:25 CST 2019 aarch64 Android`
            
      + OxygenOS version: 9.0.16
      
      + Build number: ONEPLUS A6010_41_190801

  * Hardware details: OnePlus 6T
  
  * Smart card middleware name and version: ?
  
  * Smart card reader manufacturer name and reader model name: SCM SPR332 v2

  * Smart card name: OpenPGP SmartCard V2.1

Log
===

Output of `pcsc_scan`:

    Using reader plug'n play mechanism
    Scanning present readers...
    Waiting for the first reader...   [3D - [3D \ [3D | [2D [2D

Output of `tsudo LIBCCID_ifdLogLevel=0x000F pcscd --foreground --debug --apdu --color`: [log.txt](https://github.com/LudovicRousseau/pcsc-tools/files/3666624/log.txt)

**Comment by feklee** [comment]
I forgot the output of `lsusb` (BusyBox, no `-v` option) with the reader connected:

    Bus 001 Device 001: ID 1d6b:0002
    Bus 001 Device 002: ID 04e6:e003
    Bus 002 Device 001: ID 1d6b:0003

Without the reader connected, the output is empty.

**Comment by feklee** [comment]
Concerning how I got the reader to work with GnuPG in the past, see my gist: [GnuPG on Termux for accessing USB smart card reader](https://gist.github.com/feklee/92f76d2c8a7cabc477360d82b5305c19)

**Comment by LudovicRousseau** [comment]
Strange. I don't see any log from the CCID driver in your pcscd trace.

Also you have `configdir=/data/data/com.termux/files/usr/etc/reader.conf.d` but your log contains:
```
00000392 configfile.l:360:DBGetReaderList() Parsing conf file: /etc/reader.conf.d
```

**Comment by feklee** [comment]
It's definitely the same `pcscd`. I just generated the log again using the full path for the executable.

I'm lost here. Maybe I should try compiling `pcscd` from source.

**Comment by LudovicRousseau** [comment]
Maybe. I can't support binaries provided by others.

You can also ask for help on the MUSCLE mailing list https://lists.infradead.org/mailman/listinfo/pcsclite-muscle
