### ISSUE TITLE
Card state: Card inserted, Unresponsive card

### ISSUE THREAD

**Issue by BenyuXu** [LudovicRousseau/pcsc-tools#29]
hi, 

I have two SmartCard Reader keyboards and some Siemens SLE 4432/42 card.
One keyboard has ACR38 reader, and the other is DELL KB813.
when I insert the card into the ACR38 keyboard, pcsc_scan worked well and showed like below:

> PC/SC device scanner
> V 1.4.25 (c) 2001-2011, Ludovic Rousseau <ludovic.rousseau@free.fr>
> Compiled with PC/SC lite version: 1.8.14
> Using reader plug'n play mechanism
> Scanning present readers...
> 0: ACS ACR38U-CCID 00 00
> 
> Wed Oct 16 22:42:46 2019
> Reader 0: ACS ACR38U-CCID 00 00
>   Card state: Card inserted,
>   ATR: 3B 04 92 23 10 91
> 
> ATR: 3B 04 92 23 10 91
> + TS = 3B --> Direct Convention
> + T0 = 04, Y(1): 0000, K: 4 (historical bytes)
> + Historical bytes: 92 23 10 91
>   Category indicator byte: 92 (proprietary format)
> 
> Possibly identified card (using /home/jr/.cache/smartcard_list.txt):
> 3B 04 92 23 10 91
>         Siemens SLE 4432/42 card
> 

then type 'lsusb' showed like below:

> 
> Bus 002 Device 003: ID 17ef:6050 Lenovo
> Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
> Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 001 Device 006: ID 072f:90cc Advanced Card Systems, Ltd ACR38 SmartCard Reader
> Bus 001 Device 005: ID 04d9:1603 Holtek Semiconductor, Inc. Keyboard
> Bus 001 Device 004: ID 058f:6254 Alcor Micro Corp. USB Hub
> Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

It seems good, but when I insert the card into DELL KB813 keyboard, pcsc_scan showed like below:

> PC/SC device scanner
> V 1.4.25 (c) 2001-2011, Ludovic Rousseau <ludovic.rousseau@free.fr>
> Compiled with PC/SC lite version: 1.8.14
> Using reader plug'n play mechanism
> Scanning present readers...
> 0: Dell Dell Smart Card Reader Keyboard 00 00
> 
> Wed Oct 16 22:39:32 2019
> Reader 0: Dell Dell Smart Card Reader Keyboard 00 00
>   Card state: Card inserted, Unresponsive card,

 then type 'lsusb' showed like below:

> Bus 002 Device 003: ID 17ef:6050 Lenovo
> Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
> Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 001 Device 003: ID 413c:2101 Dell Computer Corp. SmartCard Reader Keyboard
> Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Why pcsc_scan showed 'Unresponsive card' while the Siemens SLE 4432/42 card inserted into DELL KB813 keyboard ? would you mind to help fix it?

Many thanks!

**Comment by LudovicRousseau** [comment]
A memory card like the Siemens SLE 4432 is NOT a micro-processor card or smart card.
Some/most readers can't use memory cards.
