### ISSUE TITLE
Card state: Card inserted, Unresponsive card, 

### ISSUE THREAD

**Issue by pr0xxy** [LudovicRousseau/pcsc-tools#31]
Hi,

I have been using these tools for almost two years with no issues. Well starting last week I am getting an issue with my card reader "Unresponsive Card".  I even tried reinstalling the software packages:

pcsc-lite for Centos 7
pcsc-lite-ccid for Centos 7
perl-pcsc Centos 7
pcsc-tools Centos 7

Here is what I get when I run pcsc_scan:

PC/SC device scanner
V 1.4.25 (c) 2001-2011, Ludovic Rousseau <ludovic.rousseau@free.fr>
Compiled with PC/SC lite version: 1.8.8
Using reader plug'n play mechanism
Scanning present readers...
0: SCM Microsystems Inc. SCR 3310 [CCID Interface] (53311850713070) 00 00

Thu Jan 23 08:01:37 2020
Reader 0: SCM Microsystems Inc. SCR 3310 [CCID Interface] (53311850713070) 00 00
  Card state: Card inserted, Unresponsive card, 

Any ideas what is happening ?

**Comment by LudovicRousseau** [comment]
It looks like your smart card is dead.

**Comment by pr0xxy** [comment]
ok Thanks.

**Comment by dcruveiller** [comment]
But i get that on a brand new SLE4442 card. So what is this shit ?

**Comment by pr0xxy** [comment]
I took my card to our card department and they had me test it on a random Windows PC with a PIV card reader. Took a couple tries but now it works like nothing was ever wrong...got me. 🤷🏿‍♂️

**Comment by dcruveiller** [comment]
So you mean just trie with another computer ?

**Comment by pr0xxy** [comment]
In all honesty I cannot say that was what fixed it. All I know is when it was proven that nothing was wrong with my card I came back and tried it again on my Centos Laptop and presto it started working again.

**Comment by dcruveiller** [comment]
Ok but how can you trie with a Windows. I mean pcsc work only on Linux

**Comment by LudovicRousseau** [comment]
@dcruveiller SLE4442 is NOT a smart card but a memory card. Not all readers can read/write it.

**Comment by dcruveiller** [comment]
@LudovicRousseau ok but in the product description they said that SLE4442 is compatible with.

**Comment by dcruveiller** [comment]
@pr0xxy What is the exact name and brand of your reader ?
