### ISSUE TITLE
pcsc_scan says unresponsive card

### ISSUE THREAD

**Issue by dcruveiller** [LudovicRousseau/pcsc-tools#33]
Hey  pcsc_scan says unresponsive card but i have only one interface. how i make my card responsive ?
Here is the pcsc_scan output:
```
PC/SC device scanner
V 1.5.2 (c) 2001-2017, Ludovic Rousseau <ludovic.rousseau@free.fr>
Using reader plug'n play mechanism
Scanning present readers...
0: Alcor Micro AU9560 00 00
 
Sat Feb 22 15:10:52 2020
 Reader 0: Alcor Micro AU9560 00 00
  Card state: Card inserted, Unresponsive card
```

_Originally posted by @dcruveiller in https://github.com/LudovicRousseau/pcsc-tools/issues/9#issuecomment-589960079_

**Comment by LudovicRousseau** [comment]
What is your card?

**Comment by dcruveiller** [comment]
SLE4442 with Alcor Micro AU9560 reader

**Comment by LudovicRousseau** [comment]
According to http://www.alcorlink.com/Smart-Card-Reader-AU9560.html it should work.
Are you sure you insert the card in the correct way?
If yes, you should contact Alcor Micro.

**Comment by dcruveiller** [comment]
@LudovicRousseau Well i sent a message to alcor micro but what reader do you recommend for SLE4442 ?

**Comment by LudovicRousseau** [comment]
No idea. I don't use memory cards.
