### ISSUE TITLE
Not working correctly with Lisle Standard Card Rack 20 

### ISSUE THREAD

**Issue by avassdal** [LudovicRousseau/pcsc-tools#38]
Hello

I'm having some issues with pcsc_scan not working with Lisle Standard Card Rack 20. It is basically 20 pcsc-readers attatched to a USB hub. I have tried to edit PCSCLITE_MAX_READERS_CONTEXTS and  CCID_DRIVER_MAX_READERS, but when installing from source the readers will not be detected.

**Comment by LudovicRousseau** [comment]
Hello

Please follow https://pcsclite.apdu.fr/#support

**Comment by LudovicRousseau** [comment]
No news since more than 1 month.
Closing
