### ISSUE TITLE
Reading Memory Cards

### ISSUE THREAD

**Issue by bstin** [LudovicRousseau/pcsc-tools#41]
Hi @LudovicRousseau 

Apologies for the rather basic question, but how does one go about using scriptor to read the contents of a serial memory card (the card is using the AT24C02 chip set)?

The card reader is identified fine, and when inserting card it returns "3B 04 49 32 43 2E - German Health Insurance Card" (its not a german health insurance card but rather a member card for a local club).

**Comment by LudovicRousseau** [comment]
You should ask questions like that on the pcsclite-muscle mailing list https://lists.infradead.org/mailman/listinfo/pcsclite-muscle
