### ISSUE TITLE
pcsc_scan detecting nfc card on windows, but not on linux

### ISSUE THREAD

**Issue by silentzer** [LudovicRousseau/pcsc-tools#49]
it detects the reader (which is a bcm5880) but not the card on linux, works fine on windows

os: `Arch Linux (5.14.12-arch1-1)`
reader: `0a5c:5834 Broadcom Corp. 5880`

**Comment by LudovicRousseau** [comment]
Broadcom does not want to support contactless on GNU/Linux.

I suggest you to buy a contactless reader from another manufacturer.
Have a look at the list at https://ccid.apdu.fr/select_readers/index.html?features=contactless
