### ISSUE TITLE
pcsc_scan under Ubuntu requirements: libgtk3-perl

### ISSUE THREAD

**Issue by krumeich** [LudovicRousseau/pcsc-tools#53]
I'd like to run pcsc_scan in an Ubuntu based Docker container. Installing the pcsc-tools package requires `libgtk3-perl`. This, in turn, requires a whole host of other packages — among others — X11 and many other GUI components. This adds approximately 300 MB to the image size. 

Is ist possible to compile pcsc_scan without the dependencies to the GUI components? 

Thanks!

**Comment by LudovicRousseau** [comment]
the pcsc-tools package now **recommends** the package libgtk3-perl. This was changed in version 1.5.6-2.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955261

Install pcsc-tools from Ubuntu 21.04 or more. See https://packages.ubuntu.com/hirsute/pcsc-tools
