### ISSUE TITLE
pcsc_scan ISO/IEC 14443-4B ?

### ISSUE THREAD

**Issue by aleksas** [LudovicRousseau/pcsc-tools#56]
I'm using UART PN532. `pcsc_scan` detects visa, master cards and also smart watch (fitbit charge 4) payment card. But if fails to detect card associated with my smart phone. Does pcsc support `ISO/IEC 14443-4B` ?

Bellow nfc-poll output of detected phone nfc.

```sh
$ nfc-poll 
nfc-poll uses libnfc libnfc-1.8.0-63-g3df7f25
NFC reader: IFD-NFC opened
NFC device will poll during 36000 ms (20 pollings of 300 ms for 6 modulations)
ISO/IEC 14443-4B (106 kbps) target:
               PUPI: 54  0d  **  **  
   Application Data: 00  00  **  **  
      Protocol Info: 80  **  **  
Waiting for card removing...nfc_initiator_target_is_present: Target Released
done.
```

p.s. there are numbers under **

**Comment by LudovicRousseau** [comment]
The question is: is your pcsc-lite driver able to report ISO/IEC 14443-4B cards?

`pcsc_scan` just reports what comes from the PC/SC layer.

**Comment by aleksas** [comment]
Yes correct, looked a bit deeper and found that ifdnfc library doesn not handle  14443-4B cards
https://github.com/nfc-tools/ifdnfc/blob/master/src/ifd-nfc.c#L223-L263 
this would be the place (+ some more places in this file) to add 14443-4B card handling, correct?
