### ISSUE TITLE
How to submit misrecognized card

### ISSUE THREAD

**Issue by miniBill** [LudovicRousseau/pcsc-tools#60]
I've got a couple card that are misrecognized (e.g.: my Maestro gets recognized as a MasterCard blue)
I tried using the website https://smartcard-atr.apdu.fr/ but I see no "submit correction" button

Would it be safe to write the ATRs here or can they contain private information?

**Comment by LudovicRousseau** [comment]
An ATR does not contain any confidential information. But the same ATR can be used by different cards.

You can list your ATR here, or contact me by email.

**Comment by miniBill** [comment]
NFC:
3B 80 80 01 01 - Carta nazionale dei servizi - https://www.agid.gov.it/it/piattaforme/carta-nazionale-servizi [I didn't even know it had NFC!!!]
3B 85 80 01 20 63 CB B7 20 1B - Crédit Agricole Prepaid - Mastercard
3B 8B 80 01 00 31 C0 64 08 44 03 76 00 90 00 36 - Crédit Agricole Bank Card - Bancomat / Maestro
3B 8F 80 01 80 4F 0C A0 00 00 03 06 03 00 02 00 00 00 00 69 - OV Chipkaart https://www.ov-chipkaart.nl/home.htm

There is something weird going on with my NFC+chip reader (`InfoThink IT-102MU Reader (0114) 00 00`), where if I insert the card fast it will read it differently than if I insert it slow! (probably the NFC taking precedence or something?)

Chip - slow [notice how these are the same as NFC]:
3B 80 80 01 01 - Carta nazionale dei servizi - https://www.agid.gov.it/it/piattaforme/carta-nazionale-servizi
3B 65 00 00 20 63 CB B7 20 1B - Crédit Agricole Prepaid - Mastercard
3B 6B 00 00 00 31 C0 64 08 44 03 76 0F 90 00 36 - Crédit Agricole Bank Card - Bancomat / Maestro

Chip - fast [notice how these are different than the NFC ones]:
3B DF 18 00 81 31 FE 7D 00 6B 04 0C 01 84 01 11 01 43 4E 53 10 31 80 FC - This is actually recognized correctly! Although the link points to something specific for Tuscany, whereas I think it's better to point to https://www.agid.gov.it/it/piattaforme/carta-nazionale-servizi which is national
3B 65 00 00 20 63 CB B7 20 - Crédit Agricole Prepaid - Mastercard
3B 6B 00 00 00 31 C0 64 08 44 03 76 0F 90 00 - Crédit Agricole Bank Card - Bancomat / Maestro

**Comment by LudovicRousseau** [comment]
LIst updated.

Note that between fast and slow the difference is on the last byte.
In the 2 cases this byte is incorrect and should not be present.

https://smartcard-atr.apdu.fr/parse?ATR=3B6500002063CBB7201B
https://smartcard-atr.apdu.fr/parse?ATR=3B6B00000031C064084403760F900036
