### ISSUE TITLE
can not compile under windows

### ISSUE THREAD

**Issue by totti0858** [LudovicRousseau/pcsc-tools#65]
Under Windows 10, try to install the msys2 as suggested and download the latest code from github.

run the command: ./configure, then failed with:
-bash: ./configure: No such file or directory

run the command: autoconf , then failed with error.
configure.ac:10: warning: 'AM_CONFIG_HEADER': this macro is obsolete.
configure.ac:10: You should use the 'AC_CONFIG_HEADERS' macro instead.
../autoconf-2.71/lib/autoconf/general.m4:2434: AC_DIAGNOSE is expanded from...
aclocal.m4:1089: AM_CONFIG_HEADER is expanded from...
configure.ac:10: the top level
configure.ac:62: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:62: You should run autoupdate.
../autoconf-2.71/lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:62: the top level

run the command: autoreconf -ivf, it passed. Then run the command ./configure gain, it failed at:
checking for SCardEstablishContext... configure: error: SCardEstablishContext() not found, install pcsc-lite, or use PCSC_LIBS=...  ./configure

How can I fix this issue?

**Comment by LudovicRousseau** [comment]
Maybe use something like:
```
PCSC_LIBS=-lwinscard ./configure
```
See https://ludovicrousseau.blogspot.com/2017/05/pcscscan-on-windows.html

**Comment by totti0858** [comment]
Thanks for your help and I can compile it now.

Could you please update your page (https://ludovicrousseau.blogspot.com/2017/05/pcscscan-on-windows.html) then others will easily overcome this difficult.
