### ISSUE TITLE
Non-relevant application to strings of red color code

### ISSUE THREAD

**Issue by Ricky-Tigg** [LudovicRousseau/pcsc-tools#68]
On RPM Linux-GNU distribution. Terminal **Shell:** Bash

Hello. Outputs, the one reported [here](http://ludovic.rousseau.free.fr/softwares/pcsc-tools/)
```
PC/SC device scanner
V 1.4.9 (c) 2001-2006, Ludovic Rousseau <ludovic.rousseau@free.fr>
Compiled with PC/SC lite version: 1.3.1
[v]Scanning present readers
[r]Waiting for the first reader...found one
```
and the one produced in my system
```
$ pcsc_scan
[v]Using reader plug'n play mechanism
[r]Scanning present readers...
[r]Waiting for the first reader
```
differ from each other.

Note: expressions `[v]` and `[r]` were manual additions in order to indicate the strings that are exhibited respectively in **violet** and **red** color codes.

The application of red in respect to `Scanning present readers...` and `Waiting for the first reader` is not relevant since there is no warning involved to be expressed.

**Comment by LudovicRousseau** [comment]
The screen copy on the web site is for an old version of pcsc_scan. Maybe I should update it.
You can use `pcsc_scan -V` to know the version installed in your system.

What colour do you propose instead?

**Comment by Ricky-Tigg** [comment]
```
$ pcsc_scan -V
PC/SC device scanner
V 1.6.0 (c) 2001-2018, Ludovic Rousseau (...)
```
Before closing 
  - The mention of copyright is expressed here as `<year><hyphen><year>`. Worth noting that an **en-dash** (–), is what the usage defines for applying to range of dates, not a **hyphen** (-), which is commonly misused by people. For example, to produce an en-dash within a _LibreOffice Writer_ document; enter "_1--1_", press space. As a result "_--_" is converted into an en-dash. Otherwise as you may have not noticed yet the end year is erroneous.
- When it comes to a non-warning and non-error message string, you already have strings expressed as such either as non-colored as illustrated by `pcsc_scan -V` or colored as illustrated by `Using reader plug'n play mechanism`. Then they are pertinent sources of inspiration aren't they?

**Comment by LudovicRousseau** [comment]
I used an hyphen as in https://epiphany.law/articles/copyright/copyright-dates-single-year-or-range/
I don't think `2001--2022` will look great.

I updated the year in 85b931d0cf80534569a34fd3ba896534503c1920

You have not chosen the colour you want to use instead of red.

**Comment by Ricky-Tigg** [comment]
Look closer! Your very statement `2001--2022`, doesn't it show **two hyphens**. It does, doesn't it?. Then you can conclude by yourself that you did omit to do the instructed conversion, otherwise of course, you would have obtained `2001–2022`.

Those sources of inspiration were implicitly here to serve **your** choice. Well. you would not expect users to put words in your mouse nor to tell you what to like and not to like, for instance here, the presentation of a font. I can at best share with you what would be my choice if i were you, which is some **non-colored** strings.
