### ISSUE TITLE
compile from git fails

### ISSUE THREAD

**Issue by nickersk** [LudovicRousseau/pcsc-tools#72]
| ../git/pcsc_scan.c: In function 'main':
| ../git/pcsc_scan.c:496:45: error: 'ATR_PARSER' undeclared (first use in this function)
|   496 |         char atr_command[sizeof(atr)+sizeof(ATR_PARSER)+2+1];
|       |                                             ^~~~~~~~~~
| ../git/pcsc_scan.c:496:45: note: each undeclared identifier is reported only once for each function it appears in
| ../git/pcsc_scan.c:878:72: error: expected ')' before string constant
|   878 |                                         sprintf(atr_command, ATR_PARSER " '%s'", atr);
|       |                                                ~                       ^~~~~~~~
|       |                                                                        )

**Comment by nickersk** [comment]
possible fix:
--- a/pcsc_scan.c
+++ b/pcsc_scan.c
@@ -51,6 +51,10 @@ typedef enum

 #define TIMEOUT 3600*1000      /* 1 hour timeout */

+#ifndef ATR_PARSER
+/* command used to parse (on screen) the ATR */
+#define ATR_PARSER "ATR_analysis"
+#endif

 #ifndef SCARD_E_NO_READERS_AVAILABLE
 #define SCARD_E_NO_READERS_AVAILABLE 0x8010002E

**Comment by LudovicRousseau** [comment]
What OS are you using?

**Comment by LudovicRousseau** [comment]
Do (or redo):
```
./bootstrap
./configure
make
```

**Comment by nickersk** [comment]
thank you, works
