### ISSUE TITLE
Please add more maps to the database

### ISSUE THREAD

**Issue by sdivcom-dotcom** [LudovicRousseau/pcsc-tools#73]
Hi.  I scanned with your program pcsc_scan smart cards that I had at home and found that the cards issued by Alfa-bank Russia Visa - have ATR: 3B 68 00 00 00 73 C8 40 13 00 90 00
And also Visa cards from Inecobank from Armenia have 
ATR: 3B 68 00 00 99 02 00 D1 03 04 22 01
and Visa bisness ATR: 3B 68 00 00 99 02 00 D1 03 04 22 01
Could you please add them to the database. Thank you in advance for your project.

**Comment by LudovicRousseau** [comment]
Done.
See https://smartcard-atr.apdu.fr/parse?ATR=3B6800000073C84013009000
