### ISSUE TITLE
SCardEstablishContext: Service was stopped.

### ISSUE THREAD

**Issue by VesnaverAndrea** [LudovicRousseau/pcsc-tools#74]
Hi all,

I'm having troubles with the pcsc_scan function.
I'm using Ubuntu 22.04 TLS and I need retrieve data from a smart card. Since a couple of days the pcsc_scan function returns only the "SCardEstablishContext: Service was stopped" error.
I've altredy tried to uninstall and reinstall all the packeges, start the pcscd.service and the pcscd.socket; all the times I've received the error above.

Does anyone has any suggestion?

Thanks in advance.

**Comment by LudovicRousseau** [comment]
https://ludovicrousseau.blogspot.com/2023/04/faq-pcsc-lite-and-scardeservicestopped.html
