### ISSUE TITLE
Update to smartcard_list.txt for ATR 3BB2110010800016

### ISSUE THREAD

**Issue by bordenc** [LudovicRousseau/pcsc-tools#79]
Great work you're doing on this project. A few updates to this ATR (which I cannot submit online because there's already an entry):

1. Documentation is now at https://www.microchip.com/en-us/product/AT88SC1616C#document-table . The atmel.com link is defunct.
2. Rexall in Canada no longer uses these cards, so you can safely delete the last two lines and give it some generic identifier.

Merci!

**Comment by LudovicRousseau** [comment]
I fixed the URL. Thanks
See https://smartcard-atr.apdu.fr/parse?ATR=3BB2110010800016

I am not sure I want to remove the 2 last lines. I do not want to document only "current" card's ATR, but also get some history.
What do you think?

**Comment by bordenc** [comment]
It's your project and your decision :-) Since nobody else claims any other use – and is unlikely to since the manufacturer declares the chip obsolete – your reasoning is probably correct.

**Comment by LudovicRousseau** [comment]
Thanks for your comment.
Validity of URL is a real problem. But https://web.archive.org/ can help.
Closing then.
