### ISSUE TITLE
pcsc scan : waiting for the first reader

### ISSUE THREAD

**Issue by vindixav** [LudovicRousseau/pcsc-tools#80]
Bonjour Ludovic,
Nous essayons de faire fonctionner un lecteur de cartes vitale sur un serveur Ubuntu 22.04 LTS, nous avons essayé l'outil pcsc scan mais il reste sur "Waiting for the first reader".
J'ai désactivé les modules kernel pn533 et nfc, supprimé le dossier /lib/modules/5.15.0-87-generic/kernel/drivers/nfc/pn533 (et relancé le service pcscd), mais le scan reste toujours en attente de lecteur.
Le lecteur est bien vu en USB par le système :
root@principal:/lib/modules/5.15.0-87-generic/kernel/drivers/nfc# lsusb |grep INGENICO
Bus 001 Device 023: ID 0b00:0090 INGENICO Lecteur SESAM VITALE

Une idée de votre côté ?

Cordialement.

Xavier

**Comment by LudovicRousseau** [comment]
Ce lecteur n'est pas (encore) dans ma liste.
Il faut suivre https://ccid.apdu.fr/#CCID_compliant
