### ISSUE TITLE
Serbian ATRs

### ISSUE THREAD

**Issue by ubavic** [LudovicRousseau/pcsc-tools#89]
Hello,

Yesterday I submitted a few ATRs found on smart cards in the Serbia. I also noticed a few issues that could be improved, but I wasn't able to submit them through the web form:

1. The ATR `3b9d13813160378031c0694d54434f537302020440` is already registered as "DPI Card Guatemala", but new Serbian IDs also have the same ATR.
2. The ATR `3bb918008131fe9e8073ff614083000000df` is listed as "... the new Serbian biometric identity card ...", but that description is now outdated. This ATR was used in the first version of the Serbian eID, which was replaced in 2014 by newer Gemalto-based cards. A more accurate description would be "Discontinued Serbian identity card" or something similar.
3. The ATR `3b9f96801fc78031e073fe211b6450055100829000c5` is registered as "Sim card Team Telecom Armenia", but this ATR is also associated with SIM cards issued by Serbian MTS.
4. Mastercards with the ATR `3b6e000080318066b0840c016e0183009000` are (also) issued by UniCredit Bank in Serbia
5. Banca Intesa issues Visa cards with the ATR `3bff1300ff918131fe4141434f532046696f6e6131204c6336f4`

I tried to send you an email with this information, but your mail server rejected it.

If you like, I can open a PR.

Thank you for all your contributions to smart cards and open-source!

**Comment by LudovicRousseau** [comment]
All issues fixed.

What email did you try to use to contact me?

**Comment by ubavic** [comment]
> What email did you try to use to contact me?

ludovic.rousseau+blog@free.fr

Got following response:

```
This message was created automatically by mail delivery software.
A message that you sent has not yet been delivered to one or more of its
recipients after more than 24 hours on the queue on mx298.antispamcloud.com.

The message identifier is:     ==============
The date of the message is:    Sat, 23 Nov 2024 ===========
The subject of the message is: Serbian ATRs

The address to which the message has not yet been delivered is:

  [ludovic.rousseau+blog@free.fr](mailto:ludovic.rousseau+blog@free.fr)
    host mx2.free.fr [212.27.42.59]
    Delay reason: SMTP error from remote mail server after DATA:
    451 too many errors detected from your IP (==========), please visit http://postmaster.free.fr/

No action is required on your part. Delivery attempts will continue for
some time, and this warning may be repeated at intervals if the message
remains undelivered. Eventually the mail delivery software will give up,
and when that happens, the message will be returned to you.
```

This is the first time a spam filter rejected message from my server. No worries now, I got to you via github :)

Thanks

**Comment by LudovicRousseau** [comment]
`451 too many errors detected from your IP`: maybe a configuration issue on your side?

**Comment by LudovicRousseau** [comment]
I received your email.
You send it on `Date: Sat, 23 Nov 2024 15:21:19 +0100`.
I received in on `Tue, 26 Nov 2024 04:33:02 +0100 (CET)`.

**Comment by ubavic** [comment]
Thank you for the update. Not sure what happened.
